name: Django CI

on:
  push:
    branches: [ "test_branch", "test_emergency_unittest", "test_tasks_unittest" ]
  pull_request:
    branches: [ "test_branch" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{secrets.AGDESK_DB_NAME}}
          POSTGRES_USER: ${{secrets.AGDESK_DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.AGDESK_DB_PASSWORD}}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd Package_management
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DATABASE_URL: postgres://${{secrets.AGDESK_DB_USER}}:${{secrets.AGDESK_DB_PASSWORD}}@localhost:5432/${{secrets.AGDESK_DB_NAME}}
      run: |
        cd AgDeskDjango
        python manage.py test
